### ISSUE TITLE
TypeError: __init__() takes from 1 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by FIODDX** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#11]
when I run the train.py with dvs128gesture dataset, it says:

Traceback (most recent call last):
  File "codes/train.py", line 283, in <module>
    number_layer=number_layer).to(device)
  File "C:\Users\DDX\OneDrive\BATC_DDX\ICCV2021_DVS128\codes\models.py", line 280, in __init__
    use_max_pool=use_max_pool, alpha_learnable=alpha_learnable, detach_reset=detach_reset)
  File "C:\Users\DDX\OneDrive\BATC_DDX\ICCV2021_DVS128\codes\models.py", line 36, in create_conv_sequential
    PLIFNode(init_tau=init_tau, surrogate_function=surrogate.ATan(alpha = alpha_learnable), detach_reset=detach_reset) if
 use_plif else LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(alpha = alpha_learnable), detach_reset=detach_rese
t),
  File "C:\Users\DDX\OneDrive\BATC_DDX\ICCV2021_DVS128\codes\models.py", line 11, in __init__
    super().__init__(v_threshold, v_reset, surrogate_function, detach_reset, monitor_state)
TypeError: __init__() takes from 1 to 5 positional arguments but 6 were given

Seems like something goes wrong with the PIFNode class

**Comment by fangwei123456** [comment]
Hi, codes in this repo use old version of spikingjelly. If you run codes with new version of spikingjelly, you will get some unexpect errors.

Use the old version:
```
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
git reset --hard 73f94ab983d0167623015537f7d4460b064cfca1
python setup.py install
```

**Comment by FIODDX** [comment]
I now build a new spikingjelly0.0.0.1 environment with codes above. But I got this error：

Traceback (most recent call last):
  File "codes/train.py", line 224, in <module>
    from spikingjelly.datasets.dvs128_gesture import DVS128Gesture
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\DDX\Anaconda3\envs\spikingjelly0001\lib\site-packages\spikingjelly-0.0.0.0.1-py3.8.egg\spikingjelly\datasets\__init__.py", line 5, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\DDX\Anaconda3\envs\spikingjelly0001\lib\site-packages\spikingjelly-0.0.0.0.1-py3.8.egg\spikingjelly\datasets\nav_gesture.py", line 11, in <module>
ModuleNotFoundError: No module named 'loris'

I can't find any available version of loris.

**Comment by fangwei123456** [comment]
https://github.com/neuromorphic-paris/loris

**Comment by fangwei123456** [comment]
You can also delete `nav_gesture.py` to avoid this problem without insatlling loris if you do not use nav_gesture.

**Comment by FIODDX** [comment]
Thanks for the help.
Now I rewrite the codes with spikingjell 0.0.0.12. I try to meke the same network work on DVS128 datasets, but I got a loss without changing. Here is the network structure and training codes, what's the problem with it?

# DVS128 network 
class NeuromorphicNet(nn.Module):
    def __init__(self, T, init_tau, use_plif, use_max_pool, alpha_learnable, detach_reset):
        super().__init__()
        self.T = T
        self.init_tau = init_tau
        self.use_plif = use_plif
        self.use_max_pool = use_max_pool
        self.alpha_learnable = alpha_learnable
        self.detach_reset = detach_reset

        self.train_times = 0
        self.max_test_accuracy = 0
        self.epoch = 0
        self.conv = None
        self.fc = None
        self.boost = nn.AvgPool1d(10, 10)

    def forward(self, x):
        x = x.permute(1, 0, 2, 3, 4)  # [T, N, 2, *, *]
        out_spikes_counter = self.boost(self.fc(self.conv(x[0])).unsqueeze(1)).squeeze(1)
        for t in range(1, x.shape[0]):
            out_spikes_counter += self.boost(self.fc(self.conv(x[t])).unsqueeze(1)).squeeze(1)
        return out_spikes_counter


class DVS128GestureNet(NeuromorphicNet):
    def __init__(self, T, init_tau, use_plif, use_max_pool, alpha_learnable, detach_reset, channels, number_layer):
        super().__init__(T=T, init_tau=init_tau, use_plif=use_plif, use_max_pool=use_max_pool, alpha_learnable=alpha_learnable, detach_reset=detach_reset)
        w = 128
        h = 128
        self.conv = create_conv_sequential(2, channels, number_layer=number_layer, init_tau=init_tau, use_plif=use_plif,
                                           use_max_pool=use_max_pool, alpha_learnable=alpha_learnable, detach_reset=detach_reset)
        self.fc = create_2fc(channels=channels, w=w >> number_layer, h=h >> number_layer, dpp=0.5, class_num=11,
                             init_tau=init_tau, use_plif=use_plif, alpha_learnable=alpha_learnable, detach_reset=detach_reset)
        
        
def create_conv_sequential(in_channels, out_channels, number_layer, init_tau, use_plif, use_max_pool, alpha_learnable, detach_reset):
    conv = [
        nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=3, padding=1, bias=False),
        nn.BatchNorm2d(out_channels),
        PLIFNode(init_tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset) if use_plif else LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset),
        nn.MaxPool2d(2, 2) if use_max_pool else nn.AvgPool2d(2, 2)
    ]

    for i in range(number_layer - 1):
        conv.extend([
            nn.Conv2d(in_channels=out_channels, out_channels=out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
        PLIFNode(init_tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset) if use_plif else LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset),
            nn.MaxPool2d(2, 2) if use_max_pool else nn.AvgPool2d(2, 2)
        ])
    return nn.Sequential(*conv)


def create_2fc(channels, h, w, dpp, class_num, init_tau, use_plif, alpha_learnable, detach_reset):
    return nn.Sequential(
        nn.Flatten(),
        layer.Dropout(dpp),
        nn.Linear(channels * h * w, channels * h * w // 4, bias=False),
        PLIFNode(init_tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset) if use_plif else LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset),
        layer.Dropout(dpp),
        nn.Linear(channels * h * w // 4, class_num * 10, bias=False),
        PLIFNode(init_tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset) if use_plif else LIFNode(tau=init_tau, surrogate_function=surrogate.ATan(alpha=alpha_learnable), detach_reset=detach_reset),
    )
    class_num = 11
    from spikingjelly.datasets.dvs128_gesture import DVS128Gesture

    train_data_loader = torch.utils.data.DataLoader(
        dataset=DVS128Gesture(dataset_dir, train=True, frames_number=T,
                              split_by=split_by, data_type='frame'
                              # normalization=normalization
                              ),
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        drop_last=True,
        pin_memory=True)
    test_data_loader = torch.utils.data.DataLoader(
        dataset=DVS128Gesture(dataset_dir, train=False, frames_number=T,
                              split_by=split_by, data_type='frame'),
        batch_size=batch_size,
        shuffle=False,
        num_workers=4,
        drop_last=False,
        pin_memory=True)
    net = DVS128GestureNet(T=T, init_tau=init_tau, use_plif=use_plif, use_max_pool=use_max_pool,
                                  alpha_learnable=alpha_learnable, detach_reset=detach_reset, channels=channels,
                                  number_layer=number_layer).to(device)

    print(net)
    optimizer = torch.optim.Adam(net.parameters(), lr=learning_rate)
    log_data_list = []
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=T_max)
    #training
    for net.epoch in range(net.epoch, max_epoch):
        start_time = time.time()
        log_data_list.append([])
        print(f'epoch={net.epoch}')
        net.train()
        for i, [img, label] in enumerate(train_data_loader):
            img = img.to(device)
            label = label.to(device)
            img = img.type(torch.cuda.FloatTensor)
            label = label.type(torch.cuda.FloatTensor)
            optimizer.zero_grad()
            out_spikes_counter = net(img)
            out_spikes_counter_frequency = out_spikes_counter / net.T
            loss = F.mse_loss(out_spikes_counter_frequency, F.one_hot(label.unsqueeze(0).to(torch.int64), class_num).float())
            accuracy = (out_spikes_counter_frequency.argmax(dim=1) == label).float().mean().item()
            loss.backward()
            optimizer.step()
            functional.reset_net(net)
            net.train_times += 1
        scheduler.step()

**Comment by fangwei123456** [comment]
Hi, this network has been used as the tutorial. You can use it directly:

https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/classify_dvsg.html

**Comment by fangwei123456** [comment]
This doc is for the latest developing version. If you use the stable version (e.g., install from PIP), please use the doc for the stable version:

https://spikingjelly.readthedocs.io/zh_CN/0.0.0.0.12/

**Comment by FIODDX** [comment]
thanks again for your patient help!
 Since the link of origin in pages is no longer available anymore([spikingjelly.clock_driven.examples.classify_dvsg](https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/clock_driven/examples/classify_dvsg.py)), where can I find the full codes of stable version of classify_dvsg.py?

**Comment by fangwei123456** [comment]
https://github.com/fangwei123456/spikingjelly/blob/0.0.0.0.12/spikingjelly/clock_driven/examples/classify_dvsg.py
