### ISSUE TITLE
模型训练时间超过4小时后，每个epoch都会保存

### ISSUE THREAD

**Issue by yizx6** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#12]
这段代码貌似有点问题。ckpt_time应该要重新赋值。
https://github.com/fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron/blob/f644ff652f8551021c8b45d5702f38b92a3bce72/codes/train.py#L378

**Comment by fangwei123456** [comment]
是的，但这个是论文原始代码，就不做修改了
