### ISSUE TITLE
PLIFNode缺少spiking()

### ISSUE THREAD

**Issue by moxueyingyan** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#7]
AttributeError: 'PLIFNode' object has no attribute 'spiking'
提示在models.py中第22行缺少spiking()函数，请问这个函数是在哪个文件里可以调用？

**Comment by fangwei123456** [comment]
这个仓库的代码需要用老版本的spikingjelly。如果用新版，切换到这个文件定义的模型：

开发版：https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/model/parametric_lif_net.py
最新稳定版(12)：https://github.com/fangwei123456/spikingjelly/blob/0.0.0.0.12/spikingjelly/clock_driven/model/parametric_lif_net.py
